# docker-compose.yml
services:
  bot:
    build: .
    container_name: portfolio-ai-bot
    env_file:
      - .env
    volumes:
      # ChromaDB: сохраняем векторную БД между перезапусками
      - ./chroma_db:/app/chroma_db
      # SQLite: история чатов и статистика
      - ./app/db:/app/app/db
      # (опционально) если используете локальные изображения
      - ./assets:/app/assets
    restart: unless-stopped
    # Если бот должен быть доступен извне (например, для вебхуков), раскомментируйте:
    # ports:
    #   - "8080:8080"
